### ISSUE TITLE
panic: runtime error: index out of range [2091008] with length 2091008

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/rac-extract-payload#128]
Hit running the rac on some files I get a panic error. The rac file is `Payload MM_20210421-104323_20210422-13335.rac`

file can be found at: https://chalmersuniversity.box.com/s/s038kk7t0xyoznysjc0rgq4c0su6l9z3

```console
$ rac -project test *.rac


2021/04/27 10:01:36 got stop packet without a start packet (Payload_MM_20210421-104323_20210422-133351.rac)
2021/04/27 10:01:37 Raw CCDImage Payload_MM_20210421-104323_20210422-133351_1301992928335388184_1.png has 1045504 pixels, but dimensions 2048 x 511
2021/04/27 10:01:37 Payload_MM_20210421-104323_20210422-133351_1301992928335388184_1.png: Found 1045504 pixels, but dimension 2048 x 511 says it should be 1046528
2021/04/27 10:01:38 got stop packet without a start packet (Payload_MM_20210421-104323_20210422-133351.rac)
2021/04/27 10:01:38 orphaned multi-package data without termination detected (Payload_MM_20210421-104323_20210422-133351.rac)
panic: runtime error: index out of range [2091008] with length 2091008

goroutine 1212 [running]:
image.(*Gray16).Gray16At(0xc003aae080, 0x400, 0x1fe, 0xc00044dcc6)
	/opt/hostedtoolcache/go/1.14.4/x64/src/image/image.go:783 +0xa2
image.(*Gray16).At(0xc003aae080, 0x400, 0x1fe, 0xbb2ee0, 0xc00044dcc6)
	/opt/hostedtoolcache/go/1.14.4/x64/src/image/image.go:775 +0x3f
image/png.(*encoder).writeImage(0xc000254f00, 0xbb1c20, 0xc00053a100, 0xbba540, 0xc003aae080, 0xc, 0xffffffffffffffff, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.4/x64/src/image/png/writer.go:465 +0x1362
image/png.(*encoder).writeIDATs(0xc000254f00)
	/opt/hostedtoolcache/go/1.14.4/x64/src/image/png/writer.go:531 +0xe2
image/png.(*Encoder).Encode(0xc00000e0c0, 0xbb2540, 0xc000536028, 0xbba540, 0xc003aae080, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.4/x64/src/image/png/writer.go:632 +0x371
image/png.Encode(...)
	/opt/hostedtoolcache/go/1.14.4/x64/src/image/png/writer.go:561
github.com/innosat-mats/rac-extract-payload/internal/exports.DiskCallbackFactory.func1.1(0xc000028c30, 0xc0004ba9f0, 0x7ffd6a04ceaf, 0x4, 0xc00022cee0)
	/home/runner/work/rac-extract-payload/rac-extract-payload/internal/exports/disk_writer.go:77 +0x1ce
created by github.com/innosat-mats/rac-extract-payload/internal/exports.DiskCallbackFactory.func1
	/home/runner/work/rac-extract-payload/rac-extract-payload/internal/exports/disk_writer.go:67 +0x1bb
```

**Comment by skymandr** [comment]
After communication with @OleMartinChristensen the way forward is:

- Make sure the program doesn't panic, but instead skips the image and issues a clear warning to the user as to the reason.

**Comment by skymandr** [comment]
@OleMartinChristensen There are now new binaries for download: https://github.com/innosat-mats/rac-extract-payload/releases/tag/v0.2.4
