### ISSUE TITLE
Build warning for statically linked lib

### ISSUE THREAD

**Issue by skymandr** [innosat-mats/rac-extract-payload#97]
On `make build` the following warning is issued:
```rac-extract-payload> make build
go build -ldflags='-extldflags=-static' ./...
# github.com/innosat-mats/rac-extract-payload/cmd/rac
/tmp/go-link-173703299/000007.o: In function `_cgo_26061493d47f_C2func_getaddrinfo':
/tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking```

**Comment by local-minimum** [comment]
This blocks execution of code such as tests from inside VSC
```
Running tool: /snap/bin/go test -timeout 30s github.com/innosat-mats/rac-extract-payload/internal/exports -run ^(TestAWSS3CallbackFactory)$

/tmp/go-build453491494/b001/exports.test: error while loading shared libraries: libjpeg.so.9: cannot open shared object file: No such file or directory
FAIL	github.com/innosat-mats/rac-extract-payload/internal/exports	0.001s
FAIL
```

**Comment by skymandr** [comment]
This also causes runtime problems, _e.g._:
```rac-extract-payload> ~/go/bin/rac -aws -project skytest ~/Downloads/MyArchive1_20200322-2*
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fad6e3c6448]

runtime stack:
runtime.throw(0xac5473, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:679 +0x46a

goroutine 47 [syscall]:
runtime.cgocall(0x8c2dd0, 0xc00003ddc0, 0xc00974c620)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00003dd90 sp=0xc00003dd58 pc=0x403f7b
net._C2func_getaddrinfo(0xc0056b0450, 0x0, 0xc00c12f5f0, 0xc00974c620, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:92 +0x55 fp=0xc00003ddc0 sp=0xc00003dd90 pc=0x5c85a5
net.cgoLookupIPCNAME.func1(0xc0056b0450, 0x2e, 0x2e, 0xc00c12f5f0, 0xc00974c620, 0x0, 0xc00003dea0, 0x5ca5d2)
	/usr/local/go/src/net/cgo_unix.go:161 +0xd2 fp=0xc00003de08 sp=0xc00003ddc0 pc=0x5ccbd2
net.cgoLookupIPCNAME(0xaad9e4, 0x3, 0xc0059c6240, 0x2d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:161 +0x183 fp=0xc00003df18 sp=0xc00003de08 pc=0x5c9813
net.cgoIPLookup(0xc004a0cc60, 0xaad9e4, 0x3, 0xc0059c6240, 0x2d)
	/usr/local/go/src/net/cgo_unix.go:218 +0x67 fp=0xc00003dfb8 sp=0xc00003df18 pc=0x5c9f47
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00003dfc0 sp=0xc00003dfb8 pc=0x462791
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:228 +0xc7

goroutine 1 [runnable]:
encoding/binary.Size(0xa70b60, 0xc005b575e0, 0xa70b60)
	/usr/local/go/src/encoding/binary/binary.go:395 +0x11c```
[...]
